### ISSUE TITLE
Screen Output Not Suppressing

### ISSUE THREAD

**Issue by tjstrunk** [ofloveandhate/bertini_real#51]
I've tried using `bertini_real -verb 0`
`bertini_real -verb 1`
and `bertini_real -verb 2` to try and get bertini_real to stop outputting to the screen...doesn't seem to be working. I still am getting a looooot--if not all--the output to the screen that bertini_real normally does. However, perhaps there is a difference that I'm just not catching, and maybe bertini_real prints to the screen in case there are things that the user needs to further input (which I've seen before while using bertini_real but is not the case for any of the things I'm using it to do right now.)

I'd like to have 0 output to the terminal if possible. I don't know if that's an option.

**Comment by ofloveandhate** [comment]
the higher the `verb` level, the more output.  try a negative value, but i don't think there is a level that makes bertini_real or sampler silent.  instead, redirect the output to `/dev/null`, for example.  like
```
bertini_real -input myfile > /dev/null
```

or, since i think you might want to look at the output later, consider redirecting to a programmatically named file instead.

does that work for you?

**Comment by tjstrunk** [comment]
Success! Thank you! (I now know enough that this is a standard linux trick when writing a command.)
